[phases.setup]
cmds = [
  "mkdir -p /app/storage",
  "chmod 755 /app/storage"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT index.php"